# Generated by Django 4.2.3 on 2023-07-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_inner', models.CharField()),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('call_start_date', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Outgoing'), (2, 'Incoming'), (3, 'Outgoing W Redirect'), (4, 'Reverse')])),
                ('call_id', models.CharField()),
                ('duration', models.IntegerField()),
                ('record_url', models.FileField(upload_to='calls/%Y/%m/%d')),
            ],
        ),
    ]
