# Generated by Django 4.2.3 on 2023-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calluploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmodel',
            name='call_id',
            field=models.CharField(blank=True),
        ),
    ]
