# Generated by Django 4.2.3 on 2023-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calluploader', '0002_alter_callmodel_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmodel',
            name='record_url',
            field=models.FileField(blank=True, null=True, upload_to='calls/%Y/%m/%d'),
        ),
    ]
